spring.application.name=ai-interview

spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=FauzyDB

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.flyway.enabled=true

# ==============local==============
gemini.api-key=AIzaSyCHW8DI2L6-bRuI8aBhWvMKJ2rdaCOKSbY
gemini.model=gemini-2.5-flash
# url_gemini=https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent

# STT Configuration
stt.url=http://127.0.0.1:8000/media/transcribe
# stt.url=http://34.105.152.57:8000/media/transcribe
