spring.application.name=ai-interview

spring.profiles.active=prod

server.forward-headers-strategy=framework

spring.servlet.multipart.max-file-size=200MB
spring.servlet.multipart.max-request-size=200MB

spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=FauzyDB

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.flyway.enabled=true

# ==============staging==============
gemini.api.key=${GEMINI_API_KEY:}
gemini.model=gemini-2.5-flash

# STT Configuration
stt.url=http://ai-interview-stt:8000/media/transcribe

minio.url: http://minio:9001
minio.access-key: minioadmin
minio.secret-key: minioadmin
minio.bucket: ai-interview

#==============local==============
# gemini.model=gemini-2.5-flash

# STT Configuration
# stt.url=http://34.105.152.57:8000/media/transcribe

# minio.url: http://localhost:9000
# minio.access-key: minioadmin
# minio.secret-key: minioadmin
# minio.bucket: ai-interview
