spring.application.name=ai-interview

server.forward-headers-strategy=framework

spring.servlet.multipart.max-file-size=200MB
spring.servlet.multipart.max-request-size=200MB

spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=FauzyDB

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.flyway.enabled=true

# ==============local==============
gemini.api-key=AIzaSyD45xq1V3jCm6VCsALWY_yT6xCX7-O22n4
gemini.model=gemini-2.5-flash

# STT Configuration
stt.url=http://127.0.0.1:8000/media/transcribe

minio.url: http://localhost:9000
minio.access-key: minioadmin
minio.secret-key: minioadmin
minio.bucket: ai-interview
